# Site settings
title: SARS-CoV-2 
subtitle: lineages
email: aine.otoole@ed.ac.uk
description: Resources for assigning global lineages
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cov-lineages.github.io/lineages-website" # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
